server:
  port: 8761

spring:
  application:
    # 集群环境下spring.application.name必须一样,否则集群搭建失败
    name: cloud-eureka-server
  cloud:
    inetutils:
      # 设置读取网卡信息时间 默认1秒太短
      timeout-seconds: 10
eureka:
  #environment: dev
  instance:
    instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port}
    hostname: eureka-server8761.com
    # 优先使用IP地址?  下面2项会使hostname方式失效.二选一即可
    #prefer-ip-address: true
    #ip-address: ${spring.cloud.client.ip-address}
  server:
    # 自我保护模式，当出现出现网络分区、eureka在短时间内丢失过多客户端时，会进入自我保护模式，即使一个服务长时间没有发送心跳，eureka也不会将其删除，默认为true
    enable-self-preservation: true
  client:
    # 开启健康检查, 在心跳包中会包含当前应用的健康数据(由Spring Boot Actuator提供)
    healthcheck:
      enabled: true
    # false表示不向注册中心注册自己。
    register-with-eureka: true
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
    service-url:
      defaultZone: http://eureka-server8762.com:8762/eureka/

