server:
  port: 8080
  tomcat:
    mbeanregistry:
      enabled: true
spring:
  # TODO 使用配置中心和bus总线时, 注意打开此配置
#  rabbitmq:
#    host: 192.168.175.200
#    port: 5673
#    username: guest
#    password: guest
  #application:
  #  name: cloud-order-service
  cloud:
    inetutils:
      # 设置读取网卡信息时间 默认1秒太短
      timeout-seconds: 10
    # 关闭ribbon负载均衡实现
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  instance:
    prefer-ip-address: true
    #ip-address: ${spring.cloud.client.ip-address}
    instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port}
  client:
    # 开启健康检查, 在心跳包中会包含当前应用的健康数据(由Spring Boot Actuator提供)
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka-server8762.com:8762/eureka/,http://eureka-server8761.com:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
# feign默认设置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
# 要使用feign的日志功能,必须把feignClient接口所在包的日志级别设置为debug
logging:
  level:
    com.atguigu.cloud.api:  debug

# 端点监控

management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
  endpoints:
    web:
      exposure:
        # 使用spring-cloud-config-server时, 请启用refresh端点, 用于刷新@ConfigurationProperties和@RefreshScope
        # org.springframework.cloud.endpoint.RefreshEndpoint.refresh  POST /actuator/refresh 该端点会重新绑定@ConfigurationProperties和刷新@RefreshScope标注的域中的对象
        # 启用 POST /actuator/env (有请求体)端点:  用于手动添加环境变量
        # 使用spring-cloud-bus时的机制同上, 会调用所有相关应用的refresh端点
        # ConfigurationPropertiesRebinder  LoggingRebinder RefreshScope类中的refreshAll()方法
        include: "*"
      base-path: /actuator
  # 对应不带任何参数的获取数据的请求, 端点会自动缓存响应, 可以使用如下方式配置缓存时间
  endpoint:
    beans:
      cache:
        time-to-live: 10s
    health:
      show-details: always
      show-components: always
  # 为执行器配置与应用不同的port 适用于内网监控. tomcat可以同时监听多个端口
#  server:
#    port: 8081
# 打开debug模式, 查看自动配置类失效原因
debug: true